version: '3'
services:
  laravel:
    build: ./dockerfiles
    container_name: cure_php
    restart: unless-stopped
    volumes:
      - ".:/var/www"
      - "./dockerfiles/config/php/php-fpm.conf:/etc/php-fpm.conf"
      - "./dockerfiles/config/php/www.conf:/etc/php-fpm.d/www.conf"
      - "./dockerfiles/config/php/php.ini:/usr/local/etc/php/php.ini"     

  nginx:
    image: nginx:latest
    container_name: cure_web
    depends_on:
      - laravel
    volumes:
      - ".:/var/www"
      - "./dockerfiles/config/nginx/default.conf:/etc/nginx/conf.d/default.conf"
    ports:
      - "8010:80"
    restart: unless-stopped

  db:
    image: mariadb:10.4
    container_name: cure_mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    ports: 
      - 8011:3306
    environment:
      MYSQL_DATABASE: datos
      MYSQL_ROOT_PASSWORD: too

  phpmyadmin:
    container_name: cure_phpmyadmin
    image: phpmyadmin/phpmyadmin
    depends_on:
      - db
    restart: unless-stopped
    ports:
      - '8012:80'
    environment:
      PMA_HOST: cure_mysql
      MYSQL_ROOT_PASSWORD: too

